import { Business, Customer, Feedback, Coupon, Campaign, DashboardMetrics } from "./types";

export const initialBusiness: Business = {
  id: "biz-1",
  name: "Trattoria & Cava Da Matteo",
  slug: "damatteo",
  category: "restaurant",
  phone: "+56 9 8452 1190",
  address: "Av. Vitacura 3565, Vitacura, Santiago",
  googleReviewUrl: "https://g.page/r/TrattoriaDaMatteoSantiago/review",
  googlePlaceId: "ChIJbX9Z-TrattoriaDaMatteo",
  minStarsForGoogle: 4,
  primaryColor: "#059669", // Emerald
  welcomeMessage: "¿Cómo estuvo tu experiencia gastronómica hoy con nosotros?",
  thankYouMessage: "¡Muchas gracias por ayudarnos a ser mejores cada día!",
  logoUrl: "🍝",
};

export const initialCustomers: Customer[] = [
  {
    id: "cust-1",
    businessId: "biz-1",
    name: "Camila Valenzuela",
    email: "camila.valenzuela@gmail.com",
    phone: "+56 9 9123 4567",
    visitsCount: 4,
    averageRating: 5.0,
    tags: ["Cliente Frecuente", "Promotor Google", "Vinos Premium"],
    createdAt: "2026-07-15T14:30:00Z",
    lastVisitAt: "2026-09-21T21:40:00Z",
  },
  {
    id: "cust-2",
    businessId: "biz-1",
    name: "Rodrigo Morales",
    email: "rmorales.ing@gmail.com",
    phone: "+56 9 8765 4321",
    visitsCount: 2,
    averageRating: 2.0,
    tags: ["Recuperación Activa", "Mesa 12", "Demora en Servicio"],
    createdAt: "2026-08-02T19:20:00Z",
    lastVisitAt: "2026-09-20T22:15:00Z",
  },
  {
    id: "cust-3",
    businessId: "biz-1",
    name: "Fernanda Soto",
    email: "fernanda.soto.m@outlook.com",
    phone: "+56 9 7321 6549",
    visitsCount: 1,
    averageRating: 5.0,
    tags: ["Nuevo Cliente", "Reseña Verificada"],
    createdAt: "2026-09-18T13:00:00Z",
    lastVisitAt: "2026-09-18T14:30:00Z",
  },
  {
    id: "cust-4",
    businessId: "biz-1",
    name: "Ignacio Echeverría",
    email: "ignacio.echev@empresa.cl",
    phone: "+56 9 6543 9870",
    visitsCount: 3,
    averageRating: 4.0,
    tags: ["Almuerzo Ejecutivo", "Ticket Alto"],
    createdAt: "2026-06-10T12:00:00Z",
    lastVisitAt: "2026-09-17T15:10:00Z",
  },
  {
    id: "cust-5",
    businessId: "biz-1",
    name: "María José Larraín",
    email: "cotelarra@gmail.com",
    phone: "+56 9 5544 3322",
    visitsCount: 5,
    averageRating: 5.0,
    tags: ["VIP", "Eventos Privados"],
    createdAt: "2026-05-22T20:00:00Z",
    lastVisitAt: "2026-09-19T23:00:00Z",
  },
];

export const initialFeedbacks: Feedback[] = [
  {
    id: "fb-101",
    businessId: "biz-1",
    customerId: "cust-1",
    customerName: "Camila Valenzuela",
    customerEmail: "camila.valenzuela@gmail.com",
    customerPhone: "+56 9 9123 4567",
    requestId: "req-1",
    rating: 5,
    comment: "¡Excelente la pasta rellena al tartufo y el maridaje sugerido por el sommelier! El ambiente de la terraza es insuperable. Ya dejé la reseña en Google con foto.",
    positiveHighlights: ["Comida insuperable", "Excelente sommelier", "Ambiente acogedor"],
    wantsContact: false,
    status: "reviewed",
    recoveryStatus: "not_needed",
    channel: "QR en Mesa",
    serviceOrStaff: "Garzón Cristóbal",
    couponId: "coup-1",
    createdAt: "2026-09-21T21:45:00Z",
  },
  {
    id: "fb-102",
    businessId: "biz-1",
    customerId: "cust-2",
    customerName: "Rodrigo Morales",
    customerEmail: "rmorales.ing@gmail.com",
    customerPhone: "+56 9 8765 4321",
    requestId: "req-2",
    rating: 2,
    comment: "Esperamos casi 45 minutos por los platos principales y el risotto llegó tibio. El mozo fue amable, pero la cocina estaba colapsada. Me gustaría hablar con el administrador.",
    negativeReasons: ["Tiempo de espera excesivo", "Temperatura de los platos", "Falta de coordinación"],
    wantsContact: true,
    status: "escalated",
    recoveryStatus: "open",
    channel: "QR en Boleta",
    serviceOrStaff: "Cocina Turno Noche",
    couponId: "coup-2",
    createdAt: "2026-09-20T22:20:00Z",
  },
  {
    id: "fb-103",
    businessId: "biz-1",
    customerId: "cust-3",
    customerName: "Fernanda Soto",
    customerEmail: "fernanda.soto.m@outlook.com",
    requestId: "req-3",
    rating: 5,
    comment: "Primera vez que venía recomendada por una amiga. El tiramisú tradicional es de los mejores que he probado en Santiago. Volveremos seguro el fin de semana.",
    positiveHighlights: ["Postres destacados", "Rápida atención"],
    wantsContact: false,
    status: "reviewed",
    recoveryStatus: "not_needed",
    channel: "Email Post-Visita",
    couponId: "coup-3",
    createdAt: "2026-09-18T14:35:00Z",
  },
  {
    id: "fb-104",
    businessId: "biz-1",
    customerId: "cust-4",
    customerName: "Ignacio Echeverría",
    customerEmail: "ignacio.echev@empresa.cl",
    requestId: "req-4",
    rating: 4,
    comment: "Muy buena opción para almuerzos con clientes. Rápido y buena carta ejecutiva. Solo sugiero mejorar el aislamiento acústico del salón principal.",
    positiveHighlights: ["Velocidad de atención", "Calidad precio"],
    wantsContact: false,
    status: "reviewed",
    recoveryStatus: "not_needed",
    channel: "QR en Mesa",
    serviceOrStaff: "Mesa 4",
    couponId: "coup-4",
    createdAt: "2026-09-17T15:15:00Z",
  },
  {
    id: "fb-105",
    businessId: "biz-1",
    customerId: "cust-5",
    customerName: "María José Larraín",
    customerEmail: "cotelarra@gmail.com",
    requestId: "req-5",
    rating: 5,
    comment: "Celebramos el aniversario familiar y nos prepararon una mesa especial con flores y copa de prosecco de cortesía. Detalles que marcan la diferencia. 10/10.",
    positiveHighlights: ["Detalles personalizados", "Atención sobresaliente"],
    wantsContact: false,
    status: "reviewed",
    recoveryStatus: "not_needed",
    channel: "WhatsApp Automatizado",
    couponId: "coup-5",
    createdAt: "2026-09-19T23:10:00Z",
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: "coup-1",
    businessId: "biz-1",
    customerId: "cust-1",
    customerName: "Camila Valenzuela",
    feedbackId: "fb-101",
    code: "GUEST-MATTEO-7749",
    token: "tok-c1",
    title: "Copa de Vino Reserva o Postre Gratis",
    description: "Válido en tu próxima cena por consumo mínimo de $30.000.",
    type: "free_item",
    discountValue: 100, // 100% discount on dessert/drink
    minPurchaseAmount: 30000,
    expiresAt: "2026-10-21T23:59:59Z",
    status: "active",
    createdAt: "2026-09-21T21:45:00Z",
  },
  {
    id: "coup-2",
    businessId: "biz-1",
    customerId: "cust-2",
    customerName: "Rodrigo Morales",
    feedbackId: "fb-102",
    code: "RECUPERA-MATTEO-9120",
    token: "tok-c2",
    title: "Cortesía de Recuperación: 25% OFF",
    description: "Descuento en toda la cuenta como disculpa por la espera.",
    type: "percentage",
    discountValue: 25,
    expiresAt: "2026-11-20T23:59:59Z",
    status: "active",
    createdAt: "2026-09-20T22:20:00Z",
  },
  {
    id: "coup-3",
    businessId: "biz-1",
    customerId: "cust-3",
    customerName: "Fernanda Soto",
    feedbackId: "fb-103",
    code: "BIENVENIDA-FS-3310",
    token: "tok-c3",
    title: "15% OFF en Segunda Visita",
    description: "Agradecimiento especial por dejarnos tu reseña en Google.",
    type: "percentage",
    discountValue: 15,
    expiresAt: "2026-10-18T23:59:59Z",
    status: "redeemed",
    createdAt: "2026-09-18T14:35:00Z",
    redeemedAt: "2026-09-21T13:45:00Z",
    redeemedByStaff: "Caja Principal - Laura",
  },
  {
    id: "coup-4",
    businessId: "biz-1",
    customerId: "cust-4",
    customerName: "Ignacio Echeverría",
    feedbackId: "fb-104",
    code: "EJECUTIVO-IE-4481",
    token: "tok-c4",
    title: "Café Gourmet o Postre de Cortesía",
    description: "Válido en horario de almuerzo con menú ejecutivo.",
    type: "free_item",
    discountValue: 100,
    expiresAt: "2026-10-17T23:59:59Z",
    status: "active",
    createdAt: "2026-09-17T15:15:00Z",
  },
  {
    id: "coup-5",
    businessId: "biz-1",
    customerId: "cust-5",
    customerName: "María José Larraín",
    feedbackId: "fb-105",
    code: "VIP-MJL-5529",
    token: "tok-c5",
    title: "Botella Prosecco di Valdobbiadene",
    description: "Cortesía VIP para tu próxima reserva de fin de semana.",
    type: "free_item",
    discountValue: 100,
    expiresAt: "2026-11-19T23:59:59Z",
    status: "active",
    createdAt: "2026-09-19T23:10:00Z",
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: "camp-1",
    businessId: "biz-1",
    name: "QR Dinámico en Mesas y Barra",
    channel: "qr_table",
    status: "active",
    delayHours: 0,
    rewardCouponTitle: "Copa de Vino o Postre Gratis",
    rewardDiscountValue: 100,
    rewardType: "free_item",
    sentCount: 382,
    completedCount: 264,
    responseRate: 69.1,
    averageRating: 4.8,
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "camp-2",
    businessId: "biz-1",
    name: "Encuesta Post-Cena (Email 2h después)",
    channel: "post_service_email",
    status: "active",
    delayHours: 2,
    rewardCouponTitle: "15% OFF en Próxima Visita",
    rewardDiscountValue: 15,
    rewardType: "percentage",
    sentCount: 194,
    completedCount: 88,
    responseRate: 45.3,
    averageRating: 4.6,
    createdAt: "2026-08-15T12:00:00Z",
  },
  {
    id: "camp-3",
    businessId: "biz-1",
    name: "WhatsApp Re-engagement Clientes Inactivos",
    channel: "whatsapp_auto",
    status: "paused",
    delayHours: 720, // 30 days
    rewardCouponTitle: "$10.000 de Regalo en Carta",
    rewardDiscountValue: 10000,
    rewardType: "fixed_amount",
    sentCount: 65,
    completedCount: 29,
    responseRate: 44.6,
    averageRating: 4.9,
    createdAt: "2026-09-01T09:00:00Z",
  },
];

export const initialMetrics: DashboardMetrics = {
  totalFeedbacks: 184,
  averageRating: 4.82,
  ratingDelta: 0.35,
  responseRatePercentage: 68.4,
  activeRecoveryCases: 1,
  totalCouponsIssued: 172,
  totalCouponsRedeemed: 118,
  redemptionRatePercentage: 68.6,
  googleReviewsRedirected: 142,
  estimatedRecoveredRevenue: 480000, // CLP
};
